# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pose_telemetry_pb2 as pose__telemetry__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pose_telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PoseTelemetryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPoses = channel.stream_unary(
                '/com.arpose.PoseTelemetry/StreamPoses',
                request_serializer=pose__telemetry__pb2.PoseData.SerializeToString,
                response_deserializer=pose__telemetry__pb2.PoseResponse.FromString,
                _registered_method=True)


class PoseTelemetryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPoses(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoseTelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPoses': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamPoses,
                    request_deserializer=pose__telemetry__pb2.PoseData.FromString,
                    response_serializer=pose__telemetry__pb2.PoseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.arpose.PoseTelemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.arpose.PoseTelemetry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoseTelemetry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPoses(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.arpose.PoseTelemetry/StreamPoses',
            pose__telemetry__pb2.PoseData.SerializeToString,
            pose__telemetry__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
