# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose_telemetry.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pose_telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pose_telemetry.proto\x12\ncom.arpose\"\xa3\x01\n\x08PoseData\x12\x13\n\x0btranslation\x18\x02 \x03(\x02\x12\x10\n\x08rotation\x18\x03 \x03(\x02\x12\x15\n\rgripper_value\x18\x05 \x01(\x02\x12\x14\n\x0cstart_stream\x18\x06 \x01(\x08\x12\x16\n\x0eprecision_mode\x18\x07 \x01(\x08\x12\x15\n\rreset_mapping\x18\x08 \x01(\x08\x12\x14\n\x0cis_resetting\x18\t \x01(\x08\"0\n\x0cPoseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2P\n\rPoseTelemetry\x12?\n\x0bStreamPoses\x12\x14.com.arpose.PoseData\x1a\x18.com.arpose.PoseResponse(\x01\x42%\n\x0f\x63om.arpose.grpcB\x12PoseTelemetryProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.arpose.grpcB\022PoseTelemetryProto'
  _globals['_POSEDATA']._serialized_start=37
  _globals['_POSEDATA']._serialized_end=200
  _globals['_POSERESPONSE']._serialized_start=202
  _globals['_POSERESPONSE']._serialized_end=250
  _globals['_POSETELEMETRY']._serialized_start=252
  _globals['_POSETELEMETRY']._serialized_end=332
# @@protoc_insertion_point(module_scope)
