# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: full_robot.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'full_robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66ull_robot.proto\"^\n\x0b\x43\x61meraImage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tjpeg_data\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0f\n\x07quality\x18\x05 \x01(\x05\"\xd0\x04\n\x10RobotObservation\x12\x19\n\x11left_shoulder_pan\x18\x01 \x01(\x02\x12\x1a\n\x12left_shoulder_lift\x18\x02 \x01(\x02\x12\x17\n\x0fleft_elbow_flex\x18\x03 \x01(\x02\x12\x17\n\x0fleft_wrist_flex\x18\x04 \x01(\x02\x12\x17\n\x0fleft_wrist_roll\x18\x05 \x01(\x02\x12\x14\n\x0cleft_gripper\x18\x06 \x01(\x02\x12\x1a\n\x12right_shoulder_pan\x18\x07 \x01(\x02\x12\x1b\n\x13right_shoulder_lift\x18\x08 \x01(\x02\x12\x18\n\x10right_elbow_flex\x18\t \x01(\x02\x12\x18\n\x10right_wrist_flex\x18\n \x01(\x02\x12\x18\n\x10right_wrist_roll\x18\x0b \x01(\x02\x12\x15\n\rright_gripper\x18\x0c \x01(\x02\x12\x12\n\nx_velocity\x18\r \x01(\x02\x12\x12\n\ny_velocity\x18\x0e \x01(\x02\x12\x12\n\nz_velocity\x18\x0f \x01(\x02\x12\x16\n\x0etheta_velocity\x18\x10 \x01(\x02\x12\x15\n\rbattery_level\x18\x11 \x01(\x02\x12\x13\n\x0btemperature\x18\x12 \x01(\x02\x12\x16\n\x0e\x65mergency_stop\x18\x13 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x14 \x01(\x05\x12\x11\n\tcpu_usage\x18\x15 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x16 \x01(\x02\x12\x1d\n\x07\x63\x61meras\x18\x17 \x03(\x0b\x32\x0c.CameraImage\x12\x11\n\ttimestamp\x18\x18 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'full_robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAIMAGE']._serialized_start=20
  _globals['_CAMERAIMAGE']._serialized_end=114
  _globals['_ROBOTOBSERVATION']._serialized_start=117
  _globals['_ROBOTOBSERVATION']._serialized_end=709
# @@protoc_insertion_point(module_scope)
