"""Sourccey udev setup helpers for Raspberry Pi hardware aliases."""

from pathlib import Path
import os
import shutil
import subprocess
import tempfile
from typing import Callable

StatusFn = Callable[[str], None]

RULES_FILE_PATH = Path("/etc/udev/rules.d/99-sourccey-extra.rules")

SOURCCEY_EXTRA_UDEV_RULES = """# Sourccey optional hardware aliases
# Generated by lerobot-vulcan/setup/setup.py

# Optional bottom-front camera
SUBSYSTEM=="video4linux", KERNEL=="video*", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.1:1.0", ENV{ID_V4L_CAPABILITIES}==":capture:", ATTR{index}=="0", SYMLINK+="cameraFrontBottom"

# Optional front lidar
SUBSYSTEM=="tty", KERNEL=="ttyUSB*", ENV{ID_SERIAL}=="Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.2:1.0", SYMLINK+="lidarFront"
"""


def configure_sourccey_extra_udev(
    project_root: Path,
    print_status: StatusFn,
    print_success: StatusFn,
    print_warning: StatusFn,
    print_error: StatusFn,
) -> bool:
    """Install optional Sourccey udev aliases and reload udev."""
    if os.name == "nt":
        print_status("Skipping Sourccey extra udev setup on Windows.")
        return True

    if shutil.which("udevadm") is None:
        print_warning("udevadm not found; skipping Sourccey extra udev setup.")
        return True

    use_sudo = hasattr(os, "geteuid") and os.geteuid() != 0
    if use_sudo and shutil.which("sudo") is None:
        print_error(
            "sudo is required to install Sourccey udev rules. "
            "Re-run setup with sudo or install the rules manually."
        )
        return False

    cmd_prefix = ["sudo"] if use_sudo else []
    temp_dir = project_root / ".tmp"
    temp_dir.mkdir(exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=temp_dir,
        delete=False,
        prefix="sourccey-udev-",
        suffix=".rules",
    ) as handle:
        handle.write(SOURCCEY_EXTRA_UDEV_RULES)
        temp_rules_path = Path(handle.name)

    try:
        print_status(f"Installing Sourccey extra udev aliases to {RULES_FILE_PATH}...")
        subprocess.run(
            cmd_prefix + ["install", "-m", "644", str(temp_rules_path), str(RULES_FILE_PATH)],
            check=True,
            cwd=project_root,
        )
        subprocess.run(cmd_prefix + ["udevadm", "control", "--reload-rules"], check=True, cwd=project_root)
        subprocess.run(cmd_prefix + ["udevadm", "trigger"], check=True, cwd=project_root)
        print_success("Sourccey extra udev aliases installed: /dev/cameraFrontBottom and /dev/lidarFront")
        return True
    except subprocess.CalledProcessError as exc:
        print_error(f"Failed to install Sourccey extra udev rules: {exc}")
        return False
    finally:
        try:
            temp_rules_path.unlink(missing_ok=True)
        except OSError:
            pass
