"""Install persistent Sourccey hardware aliases on Raspberry Pi."""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable

StatusFn = Callable[[str], None]

RULES_FILE_PATH = Path("/etc/udev/rules.d/99-sourccey-hardware.rules")

SOURCCEY_UDEV_RULES = """# Sourccey hardware USB port mapping
# Generated by lerobot-vulcan/setup/setup.py

# Servo drivers
SUBSYSTEM=="tty", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.3:1.0", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666", SYMLINK+="robotRightArm"
SUBSYSTEM=="tty", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.4:1.0", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666", SYMLINK+="robotLeftArm"

# Wrist cameras
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.0-usb-0:1:1.0", SYMLINK+="cameraWristRight"
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.1-usb-0:2:1.0", SYMLINK+="cameraWristLeft"

# Front cameras
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.1-usb-0:1:1.0", SYMLINK+="cameraFrontRight"
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.0-usb-0:2:1.0", SYMLINK+="cameraFrontLeft"
SUBSYSTEM=="video4linux", KERNEL=="video*", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.1:1.0", ENV{ID_V4L_CAPABILITIES}==":capture:", ATTR{index}=="0", SYMLINK+="cameraFrontBottom"

# Front lidar
SUBSYSTEM=="tty", KERNEL=="ttyUSB*", ENV{ID_SERIAL}=="Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.2:1.0", SYMLINK+="lidarFront"
"""

EXPECTED_DEVICE_ALIASES = (
    "/dev/robotLeftArm",
    "/dev/robotRightArm",
    "/dev/cameraFrontLeft",
    "/dev/cameraFrontRight",
    "/dev/cameraWristLeft",
    "/dev/cameraWristRight",
    "/dev/cameraFrontBottom",
    "/dev/lidarFront",
)


def configure_sourccey_udev(
    project_root: Path,
    print_status: StatusFn,
    print_success: StatusFn,
    print_warning: StatusFn,
    print_error: StatusFn,
) -> bool:
    """Install all Sourccey udev aliases and reload udev."""
    if os.name == "nt":
        print_status("Skipping Sourccey udev setup on Windows.")
        return True

    if shutil.which("udevadm") is None:
        print_warning("udevadm not found; skipping Sourccey udev setup.")
        return True

    use_sudo = hasattr(os, "geteuid") and os.geteuid() != 0
    if use_sudo and shutil.which("sudo") is None:
        print_error("sudo is required to install Sourccey udev rules.")
        return False

    cmd_prefix = ["sudo"] if use_sudo else []
    temp_dir = project_root / ".tmp"
    temp_dir.mkdir(exist_ok=True)

    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=temp_dir, delete=False, prefix="sourccey-udev-", suffix=".rules"
    ) as handle:
        handle.write(SOURCCEY_UDEV_RULES)
        temp_rules_path = Path(handle.name)

    try:
        print_status(f"Installing Sourccey hardware aliases to {RULES_FILE_PATH}...")
        subprocess.run(
            cmd_prefix + ["install", "-m", "644", str(temp_rules_path), str(RULES_FILE_PATH)],
            check=True,
            cwd=project_root,
        )
        subprocess.run(cmd_prefix + ["udevadm", "control", "--reload-rules"], check=True, cwd=project_root)
        subprocess.run(cmd_prefix + ["udevadm", "trigger"], check=True, cwd=project_root)
        print_success("Sourccey hardware aliases installed: " + ", ".join(EXPECTED_DEVICE_ALIASES))
        return True
    except subprocess.CalledProcessError as exc:
        print_error(f"Failed to install Sourccey udev rules: {exc}")
        return False
    finally:
        temp_rules_path.unlink(missing_ok=True)
